import { createHash } from "node:crypto";
import { readFile, readdir, stat } from "node:fs/promises";
import { join, relative, posix } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { commitProjectEdit } from "./project-edit.ts";

const digest = (source: string) => createHash("sha256").update(source).digest("hex");
const manifestSchema = z.record(z.string(), z.string().regex(/^[a-f0-9]{64}$/));

export async function bundledGuidanceEntries(rootDirectory: string) {
  const entries = [{ path: join(rootDirectory, "AGENTS.md"), content: await readFile(new URL("../templates/project/AGENTS.md", import.meta.url), "utf8"), mode: 0o644 }];
  const root = new URL("../skills/", import.meta.url);
  async function walk(directory: URL): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const source = new URL(entry.name + (entry.isDirectory() ? "/" : ""), directory);
      if (entry.isDirectory()) await walk(source);
      else if (entry.isFile()) entries.push({
        path: join(rootDirectory, ".agents", "skills", relative(fileURLToPath(root), fileURLToPath(source))),
        content: await readFile(source, "utf8"), mode: (await stat(source)).mode & 0o777,
      });
    }
  }
  await walk(root);
  return entries;
}

/** Update only recorded generated bytes; authored guidance remains visible and intact. */
export async function refreshGuidance(root: string): Promise<void> {
  const path = join(root, ".vibecloud", "generated-guidance.json");
  const original = await readFile(path, "utf8").catch((error) => {
    if (error.code !== "ENOENT") throw error;
    return null;
  });
  const previous = original === null ? {} : manifestSchema.parse(JSON.parse(original));
  const next: Record<string, string> = {};
  const writes: Array<{ path: string, original: string | null, updated: string | null, mode?: number }> = [];
  const entries = await bundledGuidanceEntries(root);
  const currentKeys = new Set(entries.map((entry) => relative(root, entry.path)));
  for (const [key, hash] of Object.entries(previous)) {
    if (currentKeys.has(key)) {
      next[key] = hash;
      continue;
    }
    // A manifest cannot claim arbitrary application files or traversal paths.
    if (!key.startsWith(".agents/skills/vibecloud/") || posix.normalize(key) !== key || key.includes("\\")) continue;
    const file = join(root, key);
    const current = await readFile(file, "utf8").catch((error) => {
      if (error.code !== "ENOENT") throw error;
      return null;
    });
    if (current === null) continue;
    if (digest(current) === hash) writes.push({ path: file, original: current, updated: null });
    else console.warn(`Keeping authored retired guidance: ${file}. It is no longer bundled with the CLI; reconcile or remove it explicitly.`);
  }
  for (const entry of entries) {
    const key = relative(root, entry.path);
    const current = await readFile(entry.path, "utf8").catch((error) => {
      if (error.code !== "ENOENT") throw error;
      return null;
    });
    const generated = current === null || current === entry.content || previous[key] === digest(current);
    if (!generated) {
      console.warn(`Keeping authored or untracked guidance: ${entry.path}. Reconcile it with the installed CLI's guidance before using new features.`);
      continue;
    }
    if (current !== entry.content) writes.push({ path: entry.path, original: current, updated: entry.content, mode: entry.mode });
    next[key] = digest(entry.content);
  }
  const updated = JSON.stringify(next, null, 2) + "\n";
  if (updated !== original) writes.push({ path, original, updated });
  if (writes.length) await commitProjectEdit(root, { writes, moves: [] });
}
